ftv_front:
    resource: "@FTVFrontBundle/Controller/"
    type:     annotation
    prefix:   /front/

ftvapi:
    resource: "@FTVAPIBundle/Controller/"
    type:     annotation
    prefix:   /api/

articles:
    type:        rest
    resource:    FTV\APIBundle\Controller\ArticlesController
    prefix:      /api/